### PR TITLE
Issue654 sys prop and env var loaders should trim String values

### LINKED ISSUE #654: StdSysPropLoader & StdEnvVarLoader should trim String values
**Describe the bug**
System properties and environment vars are typically set in configuration files.  Why would these not be trimmed?

This refers to these two methods:
* StdEnvVarLoader.[isTrimmingRequiredForStringValues](isTrimmingRequiredForStringValues)
* StdSysPropLoader.[isTrimmingRequiredForStringValues](https://github.com/eeverman/andhow/blob/de7de6574c5e75ab76fa468e1249686a1098746a/andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java#L90)

Its likely that changing these defaults will not result in any tests breaking, but it should - tests should be added that verify the behavior.

### PR DESCRIPTION
**Pull request by eeverman**
### All Submissions:

Thank you!  Please check that...
* [x] You branched _**from the main branch**_ and the pull request is _**to the main branch**_
* [x] Your code is up to date with the latest code from main
* [x] You followed the guidelines in the [Contributing Guide](https://www.andhowconfig.org/developer-guide/how-to-contribute)?
* [x] Your code does not decrease test coverage of existing code, and is near 100% for new code
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

Fixes #654

### CODE REVIEW

**Comment by eeverman** [comment]
This PR has pulled in the changes in the other PR (add testing) so its hard to see the changes in this one.  When the other MR merges, this will be easier to see.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdEnvVarLoader.java [hunk 1]
```diff
@@ -83,7 +88,7 @@ public String getSpecificLoadDescription() {
 	
 	@Override
 	public boolean isTrimmingRequiredForStringValues() {
-		return false;
+		return true;
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdEnvVarLoader.java:91]: This is one of two functional changes.  Everything else is javadoc updates and changes to tests.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java [hunk 2]
```diff
@@ -87,7 +92,7 @@ public String getSpecificLoadDescription() {
 	
 	@Override
 	public boolean isTrimmingRequiredForStringValues() {
-		return false;
+		return true;
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java:95]: ...and the 2nd change.
