### PR TITLE
Fix loader setters

### LINKED ISSUE #555: Two of the loaders have 'add' behavior for 'set' methods
**Describe the bug**
Two of the loaders in the loader package perform an `add` when `set` is called.  They also ignore null and empty values.  The expected behavior for both would be:
* Completely replace values when `set` is called
* Set the associated collection to empty or null when `set` is called with null or empty.

The logic in MapLoader around the `map` field and `setMap` method is acceptable for these other methods, that is, letting the field's initial value be null and setting it to null if null is passed.  That can be verified by checking each loader's `load` method to ensure that there is a null check before the field is used.

Here is the list of loader methods that this applies to, all in the `org.yarnandtail.andhow.load` package:
* `FixedValueLoader.setPropertyValues` (see other issue about deprecating one of these methods)
* `FixedValueLoader.setKeyObjectPairValues`
* `KeyValuePairLoader.setKeyValuePairs`

Also update tests and docs to match.

### PR DESCRIPTION
**Pull request by alex-kar**
Fixes #555 

 * Fix setters for loaders.
 * Fix/add unit tests.

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

### CODE REVIEW

**Comment by alex-kar** [comment]
@eeverman Please, check the build script. Failed to install maven.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java [hunk 1]
```diff
@@ -121,8 +124,12 @@ public boolean isUnknownPropertyAProblem() {
...
 	@Override
 	public void releaseResources() {
-		values.clear();
-		keyObjectPairValues.clear();
+		if (values != null) {
+			values.clear();
+		}
+		if (keyObjectPairValues != null) {
+			keyObjectPairValues.clear();
+		}
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java:132]: This is a minor point, but these could just be set back to null with no logic.  That would return it back to its initial state and completely release resources.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java [hunk 2]
```diff
@@ -191,21 +193,73 @@ public void happyPathViaPropertyValuesAsArrayTest() {
...
+		props.add(new PropertyValue(DBL_NUMBER, "123.456D"));	//as string
+		props.add(new PropertyValue(FLAG_TRUE, " false "));
+		props.add(new PropertyValue(FLAG_FALSE, " true "));
+		props.add(new PropertyValue(FLAG_NULL, " true "));
+
+		FixedValueLoader cll = new FixedValueLoader();
+		cll.setPropertyValues(props);
+
+		cll.setPropertyValues((List<PropertyValue>) null);
+		LoaderValues result = cll.load(appDef, appValuesBuilder);
```
Comment (eeverman) [inline andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java:220]: The name 'cll' is not important, but in case you are wondering, that probably originated with a test for the StdMainStringArgsLoader, which might also be called the **C**ommand **L**ine **L**oader, since it loads arguments from the Command Line (and received by the main(String[] args)).

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java [hunk 3]
```diff
@@ -191,21 +193,73 @@ public void happyPathViaPropertyValuesAsArrayTest() {
 		assertEquals(Boolean.FALSE, result.getExplicitValue(FLAG_TRUE));
 		assertEquals(Boolean.TRUE, result.getExplicitValue(FLAG_FALSE));
 		assertEquals(Boolean.TRUE, result.getExplicitValue(FLAG_NULL));
+	}
+
+	@Test
+	public void nullValuesTest() {
```
Comment (eeverman) [inline andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java:199]: There are actually two methods that set property values that should have a 'set null' test:  The `setPropertyValues` method (tested here) and the `setKeyObjectPairValues` method, which I think is not tested for `null`.

**Review by eeverman — CHANGES_REQUESTED** [review]
This is a good change overall, but it would be nice to pick up a few more lines that are missed in the testing.

**Comment by eeverman** [comment]
@alex-kar I missed your message about the appveyor build script.  I just logged into Appveyor and was able to run it w/o problem.  I think it just hit a transient issue.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java (hunk 1 above)
Comment (alex-kar) [reply andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java]: Fixed
Should we align MapLoader#releaseResources() ?
In current implementation clears the map
```
public void releaseResources() {
    if (map != null) {
        map.clear();
    }
}
```

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java (hunk 2 above)
Comment (alex-kar) [reply andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java]: Renamed to `loader`

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java (hunk 1 above)
Comment (eeverman) [reply andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java]: All the loaders can use
```
[any resource] = null;
```
in `releaseResources()`.  At this point the loaders are done and they cannot be used again.  Resources aren't dumped immediately by the loader when the `load()` method completes because it can be useful to debug the state of how the load happened to have all that info.  But once the load succeeds completely, we don't want to hold any unneeded state because that would be held for the life of the application for no reason.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java (hunk 3 above)
Comment (alex-kar) [reply andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java]: Added tests.
For some reason I couldn't open it before, but now yes, I have access to it.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java (hunk 1 above)
Comment (alex-kar) [reply andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java]: Fixed MapLoader#releaseResources as well

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java [hunk 4]
```diff
@@ -62,14 +60,19 @@ public void setPropertyValues(PropertyValue... values) {
...
 	@Override
 	public LoaderValues load(StaticPropertyConfigurationInternal appConfigDef, ValidatedValuesWithContext existingValues) {
 
+		if (values == null) {
+			values = new ArrayList<>();
+		}
+		if (keyObjectPairValues == null) {
+			keyObjectPairValues = new ArrayList<>();
+		}
+
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java:75]: I'm glad you caught this - potentially nulls.

Rather than initialize them, I propose leaving them as potential null and wrap each of the values.stream() w/ a null check:
```
if (values != null) {
  values.stream()....
}
```
`vvs` can just be initialized to the default ArrayList size, or use a ternary expression for null.
I

**Review by eeverman — CHANGES_REQUESTED** [review]
One more small change - See note on the FixedValueLoader.
Otherwise I think its ready to go.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java (hunk 4 above)
Comment (alex-kar) [reply andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java]: Fixed

**Review by eeverman — APPROVED** [review]
Perfect - Thank you!
