### PR TITLE
MapLoader#setMap should copy the map (#554)

### LINKED ISSUE #554: MapLoader.setMap should copy the map
**Describe the bug**
The [MapLoader.setMap](https://github.com/eeverman/andhow/blob/69af75fc21aaf7194ecbf5df7bb62613755374c7/andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java#L21) method currently keeps the passed map.  Instead, this method should copy the values in the map to its own map, similar to how the [KeyValuePairLoader.setKeyValuePairs](https://github.com/eeverman/andhow/blob/69af75fc21aaf7194ecbf5df7bb62613755374c7/andhow-core/src/main/java/org/yarnandtail/andhow/load/KeyValuePairLoader.java#L56) behaves.

If an empty or null map is passed, the existing Map should be emptied and this behavior should be noted in the javadocs.

### PR DESCRIPTION
**Pull request by alex-kar**
Fixes #554 

* Fix MapLoader
* Cover with unit tests

### All Submissions:

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

### CODE REVIEW

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java [hunk 1]
```diff
@@ -10,29 +10,29 @@
  * @author eeverman
  */
 public class MapLoader extends BaseLoader implements ReadLoader {
-	
-	protected Map<?, ?> map;
-	
+
+	protected Map<?, ?> map = Collections.emptyMap();
+
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java:15]: My mistake - This will have to stay null.  Please see my comments in the issue.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java [hunk 2]
```diff
@@ -10,29 +10,29 @@
...
 	@Override
-	public LoaderValues load(StaticPropertyConfigurationInternal appConfigDef, 
+	public LoaderValues load(StaticPropertyConfigurationInternal appConfigDef,
 			ValidatedValuesWithContext existingValues) {
 		
 		Map<?, ?> props = getMap();
-		
-		if (props != null) {
+
+		if (!props.isEmpty()) {
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java:35]: I think think this will need to be `if (props != null && ! props.isEmpty()) { ...`

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java [hunk 3]
```diff
@@ -10,29 +10,29 @@
...
+	protected Map<?, ?> map = Collections.emptyMap();
+
 	protected boolean unknownPropertyAProblem = true;
 	
 	public MapLoader() {
 	}
 	
 	public void setMap(Map<?, ?> map) {
-		this.map = map;
+		this.map = map == null ? Collections.emptyMap() : new HashMap<>(map);
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java:22]: See issue comments.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java [hunk 4]
```diff
@@ -87,6 +87,6 @@ public String getLoaderDialect() {
 	
 	@Override
 	public void releaseResources() {
-		map = null;
+		map.clear();
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java:90]: This can go back to null.

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java [hunk 5]
```diff
@@ -73,7 +73,7 @@ public StdSysPropLoader() {
 	
 	@Override
 	public Map<?, ?> getMap() {
-		if (map != null) {
+		if (!map.isEmpty()) {
```
Comment (eeverman) [inline andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java:76]: This logic will need to go back to `if (map !- null)`.

The problem is that this Loader needs to distinguish between an empty map and a null map:
*  If the map is null, just use the real System.Properties
* If the map is non-null, someone is trying to override the real system properties with different values.  They may choose to override the System Properties with an empty map, meaning that they are simulating the case where there are no Sys Props.

`StdEnvVarLoader` will have the same issue.

**Review by eeverman — CHANGES_REQUESTED** [review]
Great Work - I love the added tests!

Unfortunately, I gave you some bad information.  I think the changes are small to fix my mistake, but I am very sorry.

**Comment by alex-kar** [comment]
@eeverman Thank you for your comments, please review fixes that I pushed.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+        loader.setMap(Collections.emptyMap());
+
+        assertTrue(loader.getMap().isEmpty());
+
+        // set map as null when called with null
+        loader.setMap(Collections.singletonMap("key", "value"));
+        loader.setMap(null);
+
+        assertNull(loader.getMap());
+    }
```
Comment (eeverman) [inline andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java:54]: This is a really good test of behavior - Thank you.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+
+    @Test
+    public void loadMapTest() {
+        String basePath = SimpleParams.class.getCanonicalName() + ".";
+
+        Map<String, String> args = new HashMap<>();
+        args.put(basePath + "STR_BOB", "test");
+        args.put(basePath + "STR_NULL", "not_null");
+        args.put(basePath + "STR_ENDS_WITH_XXX", "XXX");
```
Comment (eeverman) [inline andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java:63]: One suggestion:  Add some spaces around some of these values, eg:
```
args.put(basePath + "STR_BOB", "     test    ");
```
The trimmer should remove the spaces, so the result should be the same.  I should have done that in some of my tests as well.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+    }
+
+    @Test
+    public void unknownPropertyAProblemTest() {
+        assertTrue(loader.isUnknownPropertyAProblem());
+
+        loader.setUnknownPropertyAProblem(false);
+
+        assertFalse(loader.isUnknownPropertyAProblem());
+    }
```
Comment (eeverman) [inline andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java:161]: This would be a good one to add a behavior test for.  `KeyValuePairTest.testCmdLineLoaderWithUnknownProperties` is an example where this is tested.  When `isUnknownPropertyAProblem` is True, there should a 'Problem' when the loader hits an unrecognized property.  When it is false, the loader should quietly ignore them.

**Review by eeverman — CHANGES_REQUESTED** [review]
I added a few small test improvements, but this is great work!

File: andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java (hunk 4 above)
Comment (eeverman) [reply andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java]: Either way works here.

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java (hunk 7 above)
Comment (alex-kar) [reply andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java]: Fixed

File: andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java (hunk 8 above)
Comment (alex-kar) [reply andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java:161]: Fixed. Please, let me know if this is what you expected.

Comment (eeverman) [reply andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java:161]: Yep, you got it.  Nice added test.

**Review by eeverman — APPROVED** [review]
Great - Nice work!
I think I have given you permissions to merge this - are you able to?

**Comment by alex-kar** [comment]
@eeverman Thank you, I've merged it.
