### PR TITLE
Fix Issue 484 and 485

### LINKED ISSUE #484: Compilation of projects using AndHow causes warnings
**Describe the bug**
When compiling with a new JVM, warnings are generated, for example, when compiling using JDK11:
```
[WARNING] No SupportedSourceVersion annotation found on org.yarnandtail.andhow.compile.AndHowCompileProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'org.yarnandtail.andhow.compile.AndHowCompileProcessor' less than -source '11'
```

**To Reproduce**
Using Maven with JDK 11, run:
`mvn clean compile`

**Expected behavior / Actual behavior**
No warnings should be generated.

**Environment (please complete the following information):**
 - OS: MacOS 11.3.1
 - Java / JDK version: AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
 - AndHow Version: 0.4.0

**Other info**
This seems to be due to the `AndHowCompileProcessor` class, which overrides the `getSupportedSourceVersion()` instead of using the `@SupportedSourceVersion` annotation.  Apparently this is not the correct way to do that.

### LINKED ISSUE #485: Projects using AndHow fail to build in IntelliJ
**Describe the bug**
Projects using AndHow 0.4.0 fail to compile IntelliJ with an unhelpful error like this:
```
java: java.lang.IllegalArgumentException
```
This is apparently due to a bug described here:
https://youtrack.jetbrains.com/issue/IDEA-256707

Basically, IntelliJ wraps the compiler `ProcessingEnvironment` in a way that makes it break in AnnotationProcessors.  This breaking change in IntelliJ apparently arrived in version 2020.3.  Projects otherwise work if compiled directly with Maven.

**To Reproduce**
Attempt to build the AndHow Samples (using AndHow 0.4.0) project in IntelliJ 2020.3 or newer.

**Expected behavior / Actual behavior**
It should work!

**Environment (please complete the following information):**
OS: MacOS 11.3.1
Java / JDK version: AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
AndHow Version: 0.4.0
IntelliJ version 2020.3 or newer (actually tested in 2021.1.1)

### PR DESCRIPTION
**Pull request by eeverman**
Fixes #484
Fixes #485

### CODE REVIEW

File: andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java [hunk 1]
```diff
@@ -286,4 +285,38 @@ public CauseEffect(String fullClassName, Element causeElement) {
...
+				}
+			} catch (NoSuchFieldException | IllegalAccessException e) {
+				possiblyWrappedProcessingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.getMessage());
+				return null;
+			}
+		} else {
+			return possiblyWrappedProcessingEnv;	//It wasn't wrapped
+		}
+	}
+
```
Comment (eeverman) [inline andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java:321]: @vickyronnen This is really your code from a comment you had posted.
Are you OK with this being added in?

Comment (VickyRonnen) [reply andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java:321]: Yes it is.
Please include the link https://youtrack.jetbrains.com/issue/IDEA-256707 for the details and credits to Joachim Stalder for debugging the build process.
As stated in there, lombok ran into the same problems.
So my solution is the bare minimum needed for getting the thing working, it only contains plain java code for determining whether or not unwrapping is needed and then do the unwrap.
My source is developed by attaching the debugger to the build process and look into the class instances without lombok on the classpath.

Comment (eeverman) [reply andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java:321]: @vickyronnen - If I reverse this commit, could you please commit this code (or something better) directly?
I'm interested in any other ideas you have to make this better.
Thank you!
